linebender/runebender

Cargo.lock
Cargo.toml
examples/ufo_toy.rs
src/bin/glyph_editor.rs

hacky and probably not correct, but a quick first pass at displaying a glyph loaded from a UFO.

First pass at a UFO viewer

---

src/bin/glyph_editor.rs

This adds the ability to click and drag points.
My expectation (famous last words) is that all of this code will eventually be thrown out, but I think it's useful as a demo/experiment.

Mouse interactions & modifying existing points

---

src/widgets/glyph.rs

just for fun, this adds the drawing of glyph names under glyphs. This is mostly intended as a demonstration for folks that might want to play around with this 😉 @eliheuer

Draw names under glyphs

---

README.md

Caveat emptor: English is not my first language and this may not be the perfect solution/workaround.
But it is one way to get unstuck in the attempt to compile `runebender` and thus save people time and frustration.

Mention workaround to the homebrew/cairo problem

---

Cargo.lock
Cargo.toml

Repin druid

---

src/main.rs

Accept command line argument to open initial file

---

Cargo.lock
Cargo.toml
src/app_delegate.rs
src/component.rs
src/data.rs
src/design_space.rs
src/draw.rs
src/edit_session.rs
src/guides.rs
src/main.rs
src/path.rs
src/widgets/editor.rs
src/widgets/grid.rs
src/widgets/mod.rs
src/widgets/scroll_zoom.rs

This is very much 'throwing some code over the wall', but I would like to checkpoint this. As of this build we have reasonable good pan and zoom of the editor view, with drawing of paths, guidelines, and components.
We do not have any interactivity, outside of pan and zoom. (you can zoom with meta + scroll). That is the next project.

Basic editor

---

src/widgets/scroll_zoom.rs

A small tweak to try and make zooming feel better.
I had an annoying couple hours this afternoon trying to figure out how best to center the work when the content (in the scrollview) is smaller than the parent view. This is pretty difficult without being fairly tightly entwined with the scrollview, so I'm not totally sure what the plan is going to be, there. 😒

Reduce zoom scale at lower zoom levels

---

src/design_space.rs
src/path.rs
src/tools/select.rs

I was having a couple of issues with drag gestures in the select tool; this hopefully fixes those.

Fix point drag

---

src/draw.rs
src/edit_session.rs
src/menus.rs
src/tools/mod.rs
src/tools/pen.rs
src/tools/select.rs
src/widgets/editor.rs

Currently the tool can only be changed via the menu; hotkeys don't work and there is no toolbar.
---
This is a checkpoint; this is definitely rough around the edges, but I'm trying not to focus too much on polish right now and mostly just get the general structure of things in place.

Add basic pen tool

---

Cargo.lock
Cargo.toml
src/lens2.rs
src/menus.rs
src/widgets/controller.rs
src/widgets/editor.rs
src/widgets/grid.rs
src/widgets/scroll_zoom.rs

A companion for [druid #154](https://github.com/xi-editor/druid/pull/317)

Update to reflect reorganization in druid master.

---

src/app_delegate.rs
src/component.rs
src/data.rs
src/edit_session.rs
src/guides.rs
src/main.rs
src/menus.rs
src/path.rs
src/widgets/controller.rs

this gets the save panel working, and also adds basic saving for files
created by runebender.
This is currently useless because you start with an empty file and can't
add glyphs, but we'll get there shortly. 
(#56 at least gives us some starting glyphs in a new file that we can play around with)

Implement basic saving

---

src/app_delegate.rs
src/consts.rs
src/widgets/controller.rs

Update menu on save, handle save from any window

---

Cargo.lock
Cargo.toml
src/app_delegate.rs
src/component.rs
src/data.rs
src/draw.rs
src/edit_session.rs
src/main.rs
src/menus.rs
src/path.rs
src/widgets/editor.rs
src/widgets/grid.rs
src/widgets/scroll_zoom.rs

This is a set of changes motivated by wanting to automatically update the grid view during editing; this involved some tweaks to our internal model to place nice with `Data`, but the results are encouraging:
(although this gif shows that it doesn't seem to update during undo; i'll need to look into that. 😁 )

Refactor to support better state sharing

---

Cargo.lock
Cargo.toml
src/widgets/scroll_zoom.rs

Implements basic pinch-to-zoom. requires #67.

Pinch zoom

---

src/data.rs
src/main.rs
src/theme.rs
src/widgets/grid.rs

Just a little start, but I want us to define our own theme and our own constants.
This also handles drawing placeholders differently in the main view.

Add a theme module and tweak some styling stuff

---

src/main.rs
src/theme.rs
src/widgets/controller.rs
src/widgets/grid.rs
src/widgets/mod.rs
src/widgets/sidebar.rs

This doesn't do anything useful, but will eventually be where you
edit a glyphs kerning, advance, and related info.

Add Sidebar widget

---

src/main.rs
src/theme.rs

Fix broken colors, add a stroke to font title

---

src/data.rs
src/edit_session.rs
src/widgets/grid.rs

This is a rollup of three small changes that set up implementing glyph renaming.

Some small fixes

---

src/widgets/maybe.rs

I had made assumptions about when the data might change that are not
accurate; for instance, data could change in an event we never see,
and then we will receive a `Command` that has data of an unexpected type.
This removes all unwrapping; if an event arrives and we haven't yet updated to the correct widget, we will log and drop the event.

Make Maybe widget more defensive

---

Cargo.lock
Cargo.toml
src/app_delegate.rs
src/widgets/maybe.rs

This will now update when the glyph name changes.
This depends on https://github.com/xi-editor/druid/pull/869

Calculate editor window title from glyph name

---

src/data.rs
src/main.rs
src/theme.rs
src/widgets/editable_label.rs
src/widgets/fontinfo.rs
src/widgets/mod.rs
src/widgets/modal_host.rs

This adds a way to display simple modals, and uses that to pop up a view where you can edit font info.

Very basic font info editing

---

src/clipboard.rs

We do a nice thing here where we set the origin of the copied path
to (0, 0), but we were doing this individually for each subpath,
which had undesireable results.

Fix issue with "copy as code" with multiple paths

---

src/data.rs

With this patch, we correctly update things like the family and
style name when saving.

Save font info changes

---

src/app_delegate.rs
src/consts.rs
src/data.rs
src/design_space.rs
src/edit_session.rs
src/widgets/controller.rs
src/widgets/coord_pane.rs
src/widgets/editor.rs
src/widgets/mod.rs
src/widgets/toolbar.rs

This adds the ability to adjust points numerically.
Lots of rough around the edges; in particular this doesn't play nicely with undo, which I'll need to rethink a little bit. Also various little interactions are annoying. Hopefully a reasonable first pass, though?

Coordinate editor

---

src/consts.rs
src/menus.rs
src/tools/mod.rs
src/tools/pen.rs
src/tools/preview.rs
src/tools/select.rs
src/widgets/controller.rs
src/widgets/editor.rs
src/widgets/scroll_zoom.rs
src/widgets/toolbar.rs

This is a rollup of a number of patches to improve toolbar behaviour and extensibility.

Toolbar fixups

---

src/menus.rs
src/tools/mod.rs
src/tools/rectangle.rs
src/widgets/toolbar.rs

@eliheuer if you were interested in trying an ellipse tool, this patch should be a good template for how you might go about that!

Rectangle tool

---

Cargo.lock
Cargo.toml
src/mouse.rs
src/path.rs
src/tools/knife.rs
src/tools/mod.rs
src/widgets/editor.rs
src/widgets/toolbar.rs

I have some thoughts and post-mortemy stuff on this that I will save for tomorrow. Overall I'm reasonable satisfied with the outcome, although there are a few little issues:
- ~the cut line start and end points are currently quantized unnecessarily~
- ~we don't preserve tangent points~
- I have not tested robustness in all edge cases

Knife tool

---

src/data.rs
src/widgets/fontinfo.rs

These get cloned alot, and the string clone was showing up in
a profile.

Use Arc<str> instead of String in SimpleFontInfo

---

src/tools/measure.rs
src/tools/mod.rs
src/widgets/toolbar.rs

Add a measurement tool. This is fairly close to what I want it to be,
but has a few rough edges. One is the positioning of coordinate labels.
Another is the design of the icon.

Adding measure tool

---

src/edit_session.rs
src/tools/measure.rs
src/tools/mod.rs
src/tools/pen.rs

* Always round "align selection" result.
* Measure tool axis-aligns when shift is held down.

Minor touchups

---

src/theme.rs
src/widgets/editor.rs
src/widgets/grid.rs
src/widgets/scroll_zoom.rs
src/widgets/sidebar.rs

This is a few little things I cleaned up while doing some other
work.

Better theme use and some cleanup

---

src/widgets/grid.rs

This significantly cuts down on allocations.

Reuse TextLayout object in GlyphGrid

---

src/design_space.rs
src/edit_session.rs
src/path.rs
src/widgets/coord_pane.rs

This is a nice first step towards doing general transformations of
selected points.

Add selection size adjustment to CoordPane

---

Cargo.lock
Cargo.toml
src/draw.rs
src/path.rs
src/tools/ellipse.rs
src/widgets/toolbar.rs

It turns out I *was* using BezPath::nearest, although no big deal :)
this is blocked until we merge the piet update in druid: https://github.com/linebender/druid/pull/1338

Updates to new druid + piet + kurbo versions.

---

src/edit_session.rs
src/main.rs
src/quadrant.rs
src/widgets/coord_pane.rs

Another little bit of cleanup; I'll need to use this a lot more when adding selection bbox and anchors.

Move Quadrant to own file, tweak some names

---

src/draw.rs
src/path.rs

This implements more careful normalization of loaded paths,
and improves documentation of how we order points in paths.
It also reworks the draw_control_point_lines method to use
path segments, which should be more robust than indexing
into the points directly.
- fixes #160

Handle unexpected point orderings

---

src/consts.rs
src/data.rs
src/edit_session.rs
src/menus.rs
src/path.rs
src/widgets/editor.rs
src/widgets/scroll_zoom.rs

Also changes key-binding for scroll wheel zoom.

Add "reverse contours" command

---

src/draw.rs
src/edit_session.rs
src/main.rs
src/path.rs
src/selection.rs
src/tools/pen.rs
src/tools/select.rs
src/widgets/editor.rs

Just a refactor; I want to clean up some stuff before doing more selection manipulation work.

Add Selection struct and selection.rs

---

src/tools/select.rs

Two commits, with two small(ish) behaviour improvements:
The first disallows any drag gesture to begin when a click happens on a line segment;
The second explicitly allows a drag gesture to begin when a click happens on a line segment that is already selected, in which case the drag will move the selected points.

Drag improvements

---

src/selection.rs

This was a typo introduced in 6a0e554

Fix logic bug in selection iteration

---

src/data.rs

This is similar to #160; we were incorrectly assuming that a contour
would not start with an off-curve point.
- fixes #177

Fix bad conversion to BezPath when glyph starts with off-curve

---

src/widgets/toolbar.rs

Screenshot taken on macOS Big Sur:

Improve the toolbar measure tool icon

---

druid-theme-loader/src/lib.rs

This should make some failures easier to debug.

ThemeLoader errors if theme contains unknown keys

---

Cargo.lock
Cargo.toml

Update lopdf crate

---

resources/default.theme
src/draw.rs
src/theme.rs
src/widgets/editor.rs

There are still a number of magic numbers that should also
get moved, but this is a start.

Add constants from draw.rs to theme

---

runebender-lib/src/design_space.rs
runebender-lib/src/draw.rs
runebender-lib/src/edit_session.rs
runebender-lib/src/lib.rs
runebender-lib/src/path.rs
runebender-lib/src/point.rs
runebender-lib/src/point_list.rs
runebender-lib/src/tools/knife.rs
runebender-lib/src/tools/select.rs
runebender-lib/src/util.rs

This is a bunch of code that sets the stage for supporting hyperbezier paths.

Pre-hyperbezier refactor

---

runebender-lib/src/cubic_path.rs
runebender-lib/src/hyper_path.rs
runebender-lib/src/point_list.rs

Previously these were just discarded. This should help keep our
diffs more sensible.
There is still some stuff from norad that we aren't correctly
round-tripping (like lib stuff that isn't ours) but this is a step
in the right direction.

Preserve existing norad identifiers when resaving

---

runebender-lib/src/data.rs

This adds an additional step while saving.
previously we would first move the existing file to a backups
directory, and then write the new data in place. With this change,
we now first try to write the data to a temporary path, and then
on success we try to back up the existing data before finally
moving the newly saved data to the target path.
- closes #178

Make saving more atomic

---

runebender-lib/src/edit_session.rs

Fix assertion in EditSession::scale_selection

---

Cargo.lock
Cargo.toml
runebender-lib/src/tools/preview.rs
runebender-lib/src/widgets/editable_label.rs
src/main.rs

I'm mostly curious, here, to see the bloat implications
of the tracing changes.

Updates to a more recent druid rev
