linebender/runebender

- Cargo.lock
- Cargo.toml
- src/data.rs
- src/main.rs
- src/widgets/grid.rs
This handles recursion but does not check for loops, except insofar
as the recursion is actually recursive and the app will crash when
it runs out of stack space.
A complicated thing about components is that they can also have
recursive transformations; one component can include another component,
with a particular transformation, and then that whole entity can be included
as a component with a different transformation.
> Draw all components of glyph in the grid view

- src/consts.rs
- src/design_space.rs
- src/draw.rs
- src/edit_session.rs
- src/guides.rs
- src/main.rs
- src/mouse.rs
- src/path.rs
- src/tools/mod.rs
- src/tools/select.rs
- src/widgets/editor.rs
- src/widgets/mod.rs
- src/widgets/scroll_zoom.rs
The majority of this code was written a few months ago; this was
cleaning it up and adapting it to Runebender.
With this patch, it should be possible to start implementing tools,
although it is not currently possible to switch tools.
It is also now possible to, in rudimentary ways, modify the open glyph:
> Add 'tools' scaffolding and implement select tool

- Cargo.lock
- Cargo.toml
- src/consts.rs
- src/menus.rs
- src/mouse.rs
- src/widgets/editor.rs
based on #29, which should go in first.
This lets you add guides and toggle guide orientations by
right-clicking.
This also lets you crash the app, on mac, in some situations I have
not tried very hard to debug, but that's almost certainly a druid issue.
> Add basic context menu

- src/app_delegate.rs
- src/edit_session.rs
- src/main.rs
- src/menus.rs
- src/mouse.rs
- src/tools/mod.rs
- src/tools/select.rs
- src/undo.rs
- src/widgets/editor.rs
This is very non-fancy, but proves out the feature, and is wired
to the undo/redo menu items.
I'm heartened by how approximately easy this was. I'm sure there are some bugs in here (and certainly some UX tweaks) but it required no grand adjustments to architecture, which was something I was concerned about.
> Implement basic undo

- Cargo.lock
- Cargo.toml
- src/app_delegate.rs
- src/data.rs
- src/main.rs
- src/widgets/scroll_zoom.rs
No big behaviour changes except that clicking on an already open glyph in the glyph list will now bring that editor window to the front.
> App delegate tweaks

- src/consts.rs
- src/copy_as_code.rs
- src/main.rs
- src/menus.rs
- src/widgets/editor.rs
This adds a new item to the 'Glyph' menu; when selected it
will generate Rust code to represent the paths in the glyph,
and copy them to the clipboard.
generates:
```rust
let mut bez = BezPath::new();
bez.move_to((208.0, 418.0));
bez.curve_to((323.0, 418.0), (417.0, 324.0), (417.0, 209.0));
bez.curve_to((417.0, 94.0), (323.0, 0.0), (208.0, 0.0));
bez.curve_to((93.0, 0.0), (0.0, 94.0), (0.0, 209.0));
bez.curve_to((0.0, 324.0), (93.0, 418.0), (208.0, 418.0));
bez.close_path();
bez.move_to((108.0, 88.0));
bez.curve_to((67.0, 88.0), (31.0, 70.0), (0.0, 33.0));
bez.line_to((26.0, 0.0));
bez.curve_to((44.0, 29.0), (74.0, 51.0), (108.0, 51.0));
bez.curve_to((139.0, 51.0), (167.0, 34.0), (194.0, 0.0));
bez.line_to((214.0, 31.0));
bez.curve_to((188.0, 65.0), (149.0, 88.0), (108.0, 88.0)); …
```
> Add 'Copy as Code' menu item

- src/edit_session.rs
- src/widgets/editor.rs
- src/widgets/scroll_zoom.rs
This is a temporary alternative to having an actual toolbar; we just
draw the name of the current tool on the screen.
In addition this implements 'V' for select and 'P' for pen.
> Add tool hotkeys and display current tool name

- Cargo.lock
- Cargo.toml
- src/clipboard.rs
- src/edit_session.rs
- src/main.rs
- src/menus.rs
- src/path.rs
- src/plist.rs
- src/widgets/editor.rs
This is a semi-accidental patch. It implements pasting data from
binary plists with the Glyphs.app style.
It does not actually work with stuff that is put on the clipboard
_by_ glyphs, because glyphs uses string plists, which the rust
plist library does not know how to parse.
However, it _does_ mean that you can copy and paste within the app,
so I think it's worth a commit just for that case. We can deal with
other formats at a later date.
> Implement basic paste

- src/data.rs
- src/main.rs
- src/widgets/grid.rs
This is very pragmatic; we can't currently add new glyphs, so we might
as well include a few when creating a new empty font.
> Make blank font include ascii letters, add placeholder glyph

- src/clipboard.rs
- src/design_space.rs
- src/path.rs
- src/widgets/editor.rs
This gets PDF paste working. This was a bit of a headache, because
there's an odd behaviour on macOS where it seems that paths that
are both filled and stroked are included twice, the second time
after a matrix transformation. I'm sure there's a rationale for this,
but I couldn't find it, and so we apply these transforms as we
encounter them and then remove duplicate paths at the end.
----
I'd started this last week but had just left it sitting around, so figured its worth patching up and getting merged.
> Implement pasting of pdf data

- src/path.rs
When a tangent point handle was nudged onto the same coordinate as its
on curve point, we would crash when attempting to adjust the linked
off curve point; there was a division by zero leading to NaN.
> Fix crash when tangent point handle goes to bed

- Cargo.lock
- src/consts.rs
- src/draw.rs
- src/menus.rs
- src/tools/mod.rs
- src/tools/pen.rs
- src/tools/preview.rs
- src/tools/select.rs
- src/widgets/editor.rs
- src/widgets/scroll_zoom.rs
This lets you use spacebar to toggle drawing the current glyph
in 'preview mode', that is with all outlines and components filled
and no other canvas entities visible.
> Implement spacebar preview and barebones preview tool

- Cargo.lock
- Cargo.toml
- src/data.rs
- src/main.rs
- src/theme.rs
- src/widgets/controller.rs
- src/widgets/grid.rs
- src/widgets/mod.rs
- src/widgets/sidebar.rs
Widgets in the grid view are now selectable; a single click selects a glyph, and a double click opens the editor view.
When selected, we show additional info about a glyph (such as its name, advance, and codepoint) in the sidebar.
> Selectable glyphs

- src/widgets/maybe.rs
- src/widgets/mod.rs
- src/widgets/sidebar.rs
This is an experiment in a widget for representing `Option<T>`.
It has two branches, one with data `T` and one with data `()`, and
it internally switches betweem them as the data changes.
This is a specialization of the more interesting idea of a widget
for representing arbitrary enums, but I like the relative simplicity
of the implementation, and could imagine it being used more widely.
This uses the new widget to toggle whether or not to display a glyph
in the sidebar, based on whether a glyph is selected.
> Add Maybe widget

- src/data.rs
- src/widgets/sidebar.rs
Just trying this out, instead of unwrapping internally. Kind of annoying because we have to style both labels. Maybe room for some convenience labels for displaying data, with one for optional data that uses a default?
> Use Maybe to display codepoint

- src/data.rs
- src/edit_session.rs
- src/theme.rs
- src/widgets/editable_label.rs
- src/widgets/maybe.rs
- src/widgets/mod.rs
- src/widgets/sidebar.rs
This will be a useful widget in a bunch of places; the first of
these is editing a glyph's advance in the main screen. The next
will be editing the coordinate of a point.
> Add EditableLabel widget, make advance editable

- src/app_delegate.rs
This now expects to be sent to the window in question, not to the
global target.
> Fix bringing open window to front

- src/main.rs
This behaviour changed in druid recently.
> Expand width of grid scroll widget

- Cargo.lock
- Cargo.toml
- src/app_delegate.rs
- src/consts.rs
- src/data.rs
- src/menus.rs
- src/widgets/controller.rs
This adds the ability to create and delete glyphs in the main view.
This is available via commands in the 'Glyph' menu.
Deleting glyphs cannot currently be undone!
> Add and delete glyphs

- src/app_delegate.rs
- src/data.rs
- src/edit_session.rs
Doing so makes it hard to rename a glyph that is being edited.
Here we introduce a SessionId and another level of indirection
to track sessions across renames.
> Don't use GlyphName to identify edit sessions

- src/app_delegate.rs
- src/consts.rs
- src/data.rs
- src/edit_session.rs
- src/glyph_names.rs
- src/main.rs
- src/widgets/sidebar.rs
This uses the aglfn list to map from names to codepoints, and
if a name does not exist it just uses the first character in
the name. Which is not correct! totally not okay! But also maybe
the least bad thing to do, for now.
This also reworks how we actually do renaming; previously we were
doing some very fancy lens stuff, but I think it's easier to just
use a command for this.
> Calculate glyph codepoints based on name

- src/glyph_names.rs
Noticed this while drawing the icons; I do not want a glyph named
'Arrow' to automatically be assigned to 'A' :grin:
> Be less aggressive when guessing codepoints from a name

- Cargo.lock
- Cargo.toml
- src/data.rs
Saving isn't well tested at the moment and so it seems best to
be maximally cautious about user data.
This moves to moving any existing data before overwriting.
Given a file ./path/to/font.ufo, backups will be created at
./path/to/font_backups/YYYY-MM-DD_HHMMSS.ufo.
saves that occur in the same second may still cause data loss?
> Always backup an existing file before overwriting

- src/app_delegate.rs
- src/widgets/controller.rs
- src/widgets/mod.rs
- src/widgets/scroll_zoom.rs
- src/widgets/toolbar.rs
This is based on some of eli's sketches in #43.
The icons are *perhaps* a little rough, but my intention is that when the editor picks up features (ideally rapidly, over the next while) we can use it to redraw them, and we can keep them in a UFO file in source control.
> Add toolbar widget with actual icons

- src/design_space.rs
- src/edit_session.rs
- src/mouse.rs
- src/path.rs
- src/tools/knife.rs
- src/tools/pen.rs
- src/tools/select.rs
Quite a few new functions and improvements in pen and select tools.
Pen:
* Clicking on a segment splits the segment there.
* Clicking on a point only closes an open path.
* Points are only appended to open paths.
* Keyboard command for deleting the selection.
* Default "trailing" is lerped, not coincident with start.
Select:
* Clicking on a segment selects it.
* Alt-clicking a line segment upgrades it to a cubic.
Both tools:
* Hit testing is based on priorities.
And some general code improvements.
> Improvements to pen and select

- Cargo.lock
- Cargo.toml
- src/tools/rectangle.rs
- src/widgets/editable_label.rs
- src/widgets/grid.rs
This compiles, but the editable label is even more broken than before. Before, the only serious problem was that a lot of keys were being swallowed by the tool selection logic. Now, the field is blank and any attempt to edit it immediately cancels the edit.
I can try to fix it, but am a bit worried that I'm running into fundamental Druid problems dealing with dynamic changes. Right now I'm trying to focus on tool/drawing behavior.
> Update to latest Druid

- src/consts.rs
- src/edit_session.rs
- src/menus.rs
- src/path.rs
- src/widgets/editor.rs
When multiple points are selected, squash the minor axis towards the
midpoint of the bbox.
A rough edge: the command doesn't register for undo.
> Align selection command

- Cargo.lock
- Cargo.toml
- src/widgets/editable_label.rs
The previous implementation did not survive the changes to the
druid TextBox widget.
This implementation is also a bit hacky, but overall I like it
better; instead of holding onto both a label and a textbox, we
just use a textbox but synthesize its data while editing.
When we draw it as a 'label', we just grab the inner layout
object and draw it directly.
> Fix EditableLabel

- Cargo.lock
- Cargo.toml
- src/widgets/coord_pane.rs
- src/widgets/editable_label.rs
- src/widgets/fontinfo.rs
This is mostly just baseline aligning labels with their text fields and a few font tweaks.
The baseline alignment stuff won't work when an `EditableLabel` is in 'label mode' until https://github.com/linebender/druid/pull/1319 lands.
> Text improvements

- src/draw.rs
- src/edit_session.rs
- src/path.rs
This is a little part of the broader work on selection transforms;
I found it difficult to tell the extent of a multi-point selection,
and this is something that is done by all the other editors I have
played around with.
> Highlight selected segments when drawing

- src/edit_session.rs
- src/widgets/editor.rs
This was leftover from an early iteration where we didn't
have a toolbar.
> Remove tool_desc

- src/consts.rs
- src/edit_session.rs
- src/widgets/controller.rs
- src/widgets/coord_pane.rs
- src/widgets/editor.rs
Instead of modifying the data directly, the coord panel now just
sends a command to the editor asking *it* to modify the data.
> Make coord panel partipate in undo

- src/edit_session.rs
- src/path.rs
- src/tools/knife.rs
We were being a bit cavalier previously with how we manipulated
and compared EntityIds; this tries to add actual API in places
where we were previously doing a bunch of reaching into structs
and comparing things directly.
At some point we may want a more expressive representation for
an entity identifier, and this will let us be more robust
in that case.
> More principled API & use for EntityId

- src/widgets/editor.rs
If no widget is active, events that occur outside of the view
are not delivered; this means that (for instance) dragging
a selection outside of the window will cause the selection
to stop updating.
- fixes #156
> Set active state correctly when mouse is down

- src/design_space.rs
- src/edit_session.rs
- src/main.rs
- src/quadrant.rs
- src/theme.rs
- src/tools/mod.rs
- src/tools/select.rs
- src/util.rs
- src/widgets/coord_pane.rs
This implements basic scaling of the current selection by
manipulating the handles on the bounding box.
This doesn't display any text, and it doesn't implement other
transforms. Or do aspect-ratio locking. So: this is a first
pass, but it feels pretty good.
> Selection transform

- src/app_delegate.rs
- src/data.rs
- src/widgets/grid.rs
- src/widgets/sidebar.rs
This standardizes on the behaviour of exposing lenses as either
associated constants or type methods, and removes an unnecessary
level of nesting in data::lenses submodule.
> Cleanup lenses

- Cargo.lock
- Cargo.toml
- src/widgets/editable_label.rs
- src/widgets/glyph_pane.rs
This allows these labels to be draw their contents centered
or aligned to either edge, as desired.
before:
after:
> Add EditableLable::text_alignment

- src/menus.rs
Adds Ellipse, Knife, and Measure options, which currently exist in the toolbar, but not the tool menu. In PR #136 there is some discussion about the need for this update.
I tested this on both macOS 11 and elementaryOS(GTK).
> Update tools menu to reflect the current toolbar

- src/widgets/toolbar.rs
Makes the icon somewhat less abstract. The `BezPath` code has a few comments to make editing the icon easier in the future. See the macOS 11 screenshot below.
> Update the toolbar preview icon

- src/draw.rs
Some possible improvements to the point and handle UX:
- Point sizes adjusted
- Color theme updated
- Duel-color inner/outer convention introduced
- Path direction arrow color and distance from point adjusted
- New color theme element for selected points/handles
MacOS 11 screenshot:
> Improve point and handle UX

- src/draw.rs
I tested this on macOS 11 and Debian Linux, it loads non-standard x/cap-heights from UFO sources. Before this update there wasn't an easy way to see where the x and cap heights were in the metrics box.
> Add x-height and cap-height guides to the editor's metrics box

- src/theme.rs
- src/widgets/editor.rs
- src/widgets/grid.rs
Adds a new glyph box style and off-white background color
Removes the full-width baseline graphic
Spacing adjustments
See the macOS 11 screenshot below:
> Update glyph grid UI design

- runebender-lib/src/clipboard.rs
- runebender-lib/src/component.rs
- runebender-lib/src/consts.rs
- runebender-lib/src/draw.rs
- runebender-lib/src/edit_session.rs
- runebender-lib/src/guides.rs
- runebender-lib/src/lib.rs
- runebender-lib/src/path.rs
- runebender-lib/src/point.rs
- runebender-lib/src/selection.rs
- runebender-lib/src/tools/knife.rs
- runebender-lib/src/tools/rectangle.rs
This is preliminary work towards spline integration; I would like
to start breaking up path.rs in order to share as much code as
is reasonable between the bezier and hyperbezier splines.
In particular I want to use the same type to represent the actual
vec of offcurve and on-curve points; there's a bunch of fiddly logic
here, and I think it can be reasonably well isolated and reused.
This doesn't do that (although it *does* change the representation
of PointType, in anticipation of having auto points) but it lays
the groundwork.
> Move Entity, PathPoint, PointType to point.rs

- resources/dark.theme
- resources/default.theme
- runebender-lib/src/theme.rs
- runebender-lib/src/widgets/grid.rs
- This moves all hardcoded colors from `widgets/grid.rs` to the theme system
- Adds a basic dark theme
Mac OS 11.1 screenshot, note that the glyph grid cells can't be styled to fit the dark theme with hardcoded color values:
> Move hardcoded glyph grid cell colors to theme

- resources/dark.theme
- resources/default.theme
- runebender-lib/src/theme.rs
- runebender-lib/src/tools/knife.rs
Adds knife guide and intersection colors to the theme system.
MacOS 11.0.1 Screenshots of `default.theme` and `dark.theme`:
> Move knife tool colors to the theme system

- runebender-lib/src/cubic_path.rs
- runebender-lib/src/draw.rs
- runebender-lib/src/edit_session.rs
- runebender-lib/src/hyper_path.rs
- runebender-lib/src/path.rs
- runebender-lib/src/point_list.rs
- runebender-lib/src/tools/pen.rs
- runebender-lib/src/tools/select.rs
This moves to using a state machine internally to track what's happening with the pen.
This also includes two practical changes: it cleans up the logic around the 'trailing point' (the ghost off-curve point you get from a click+drag with the pen tool) and it also correctly sets the selection to the newly added point when a point is added or a path is closed.
> Pen improvements

- runebender-lib/src/design_space.rs
- runebender-lib/src/mouse.rs
- runebender-lib/src/tools/ellipse.rs
- runebender-lib/src/tools/knife.rs
- runebender-lib/src/tools/measure.rs
- runebender-lib/src/tools/mod.rs
- runebender-lib/src/tools/pen.rs
- runebender-lib/src/tools/preview.rs
- runebender-lib/src/tools/rectangle.rs
- runebender-lib/src/tools/select.rs
- runebender-lib/src/widgets/editor.rs
The previous implementation was a bit of a hack; this now implements
a real 'preview' tool that supports click and drag to pan.
Making this work also involved actually implementing mouse gesture
canceling, and adds a method to Tool that lets tools specify their
preferred default cursor.
fixes #190
> Implement panning in preview tool

- runebender-lib/src/edit_session.rs
- runebender-lib/src/path.rs
- runebender-lib/src/point_list.rs
- runebender-lib/src/selection.rs
With this patch, if you delete the last point in an open path
(for instance) the selection will be updated to the new end point.
> Select a new point in path when deleting a single point

- runebender-lib/src/edit_session.rs
- runebender-lib/src/guides.rs
- runebender-lib/src/path.rs
- runebender-lib/src/point_list.rs
- runebender-lib/src/tools/pen.rs
- runebender-lib/src/tools/select.rs
This moves to using a much richer state machine in the selection tool, and then builds on top of that to provide feedback around what the current hit target is:
https://user-images.githubusercontent.com/3330916/106782883-ae08e980-6618-11eb-8a1a-45f6dc172ccf.mov
> Richer select state

- runebender-lib/build.rs
- runebender-lib/src/theme.rs
Setting the RB_THEME_PATH env var will bake the specified path
into the binary.
fixes #215
@alerque is this suitable for your needs?
> Allow overriding theme file path at compilation time

- runebender-lib/src/hyper_path.rs
This feels like it might be a norad bug; you should not be able
to construct a Contour that has a lib section but does not have
an identifier, since saving this contour will always panic?
cc @madig, what do you think? This would panic in the
'dumb_object_libs' method of norad...
> Fix crash on save with missing identifier

- runebender-lib/src/virtual_font.rs
This is a particular problem because we always ensure .notdef is
present in the vfont, even if it doesn't exist in the font.
fixes #231
> Don't panic on missing glyph in virtual_font

- runebender-lib/src/menus.rs
Remove the Tools menu bar item for now.                               
On the GTK platform,   there is no straightforward way to disable hot­
keys while editing text,  this means that the menu bar will always re­
ceive these keys before the text input does because AccelGroups always
receive keys before DrawArea. Furthermore,  because  menus are global,
there is nothing available to  menus::make_menu  to disable these menu
items when the focused window is not a glyph editor window,   and this
will be a problem again down the line, when there are non-numeric text
inputs  (e.g. a search box for selecting components to add to a glyph)
in the glyph editor window.                                           
In the future, we can add hax to work around the GTK behavior, or may­
be we'll be onto …
> Remove the Tools menu bar item for now.

- runebender-lib/src/point_list.rs
This change allows to move only one of two offcurves, while preserving the feature that if you move an on-curve, its off-curves follow.
> Allow moving only one offcurve without touching its neighbour

- resources/default.theme
This is one of the issues from Dave's "various suggestions" issue: https://github.com/linebender/runebender/issues/224
> Change the preview fill color from magenta to black

- runebender-lib/src/widgets/toolbar.rs
I did a full redesign of the toolbar widget icons. I tried to create better visual continuity between each icon and made some adjustments to help clarify each tool's use case. Please see the screenshot below.
The UFO source file for the icons used for this PR is here: https://github.com/eliheuer/runebender-icons/tree/main/ufo-icon-source/toolsbar-icons.ufo at commit `8af9f24`.
And for reference, the screenshot below is the toolbar widget icons before the redesign.
> Add redesigned toolbar widget icons

- runebender-lib/src/widgets/coord_pane.rs
Update coordinate pane layout padding and spacers. It still needs some work, but it is an improvement from my perspective.
> Update coordinate pane layout padding and spacers

- runebender-lib/src/widgets/glyph_pane.rs
To match the layout spacing of the coordinate pane. See screenshot below:
> Update glyph-pane layout spacing

- runebender-lib/src/widgets/controller.rs
- runebender-lib/src/widgets/coord_pane.rs
- runebender-lib/src/widgets/glyph_pane.rs
- runebender-lib/src/widgets/toolbar.rs
This PR makes an update mainly attempting to improve the UI/UX for the coordinate pane, based on my experience using the editor.
- Adds a redesign of the visual style of the coordinate pane for better legibility and easier hit targets for mouse clicks
- Adjusts the font and text size of the glyph pane to match the new coordinate pane
- Adjusts the size of the toolbar for better visual harmony with the coordinate pane and icon legibility
- Adjust the controller margin for the 8 unit spacing grid used in other UI elements
- Move the coordinate pane to the right side of the window, this needs some logic that puts the coordinate pane in the center when the window is wider than 700 units still, but I thought that could be in a separate PR.
If this is too much for one PR, just let me know and I …
> Update coordinate pane and glyph edit window UI
